import { Activity, Goal, Sparkles, Target, Trophy } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PlayerCard } from "./player-card";
import { roleLabels } from "./schema";
import type { PlayerProfileData } from "./data";

export function PlayerProfileView({ data, children }: { data: PlayerProfileData; children?: React.ReactNode }) {
  const displayName = [data.profile.first_name, data.profile.last_name].filter(Boolean).join(" ") || `@${data.profile.username}`;
  return <main className="py-6 sm:py-10"><div className="grid gap-8 lg:grid-cols-[340px_1fr] lg:items-start"><div className="lg:sticky lg:top-8"><PlayerCard avatarUrl={data.avatarUrl} name={displayName} overall={data.stats.overall} role={data.profile.primary_position} stats={data.stats} username={data.profile.username} /></div><div className="space-y-5"><div><p className="text-xs font-bold tracking-[.18em] text-primary uppercase">Profilo giocatore</p><h1 className="mt-2 text-3xl font-black">{displayName}</h1><p className="mt-2 text-sm text-muted-foreground">@{data.profile.username} · {data.profile.primary_position ? roleLabels[data.profile.primary_position] : "Giocatore"}</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Partite" value={data.stats.matches} icon={<Activity />} /><Metric label="Gol" value={data.stats.goals} icon={<Goal />} /><Metric label="Assist" value={data.stats.assists} icon={<Target />} /><Metric label="MVP" value={data.stats.mvp} icon={<Trophy />} /></div><Card><CardHeader><CardTitle>Prestazioni</CardTitle></CardHeader><CardContent><div className="grid grid-cols-3 gap-3"><Small label="Vittorie" value={data.stats.wins} /><Small label="Win rate" value={`${data.stats.winRate}%`} /><Small label="Trend 5" value={`${data.trend >= 0 ? "+" : ""}${data.trend}`} /></div><div className="mt-5 flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase text-muted-foreground">Forma recente</span>{data.form.length ? data.form.map((result, index) => <Badge className={result === "win" ? "bg-primary/15 text-primary" : result === "loss" ? "bg-destructive/15 text-destructive" : ""} key={`${result}-${index}`} variant="secondary">{result === "win" ? "W" : result === "draw" ? "D" : "L"}</Badge>) : <span className="text-sm text-muted-foreground">Nessuna partita</span>}</div></CardContent></Card><RatingTrend data={data} />{children}</div></div></main>;
}

function RatingTrend({ data }: { data: PlayerProfileData }) { const points = data.history.slice(-10); const min = Math.min(...points.map((point) => point.rating), 69); const max = Math.max(...points.map((point) => point.rating), 71); return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="text-primary" />Andamento overall</CardTitle></CardHeader><CardContent>{points.length ? <div><div className="flex h-28 items-end gap-2">{points.map((point) => <div className="flex h-full flex-1 flex-col justify-end" key={point.id}><div className="rounded-t-md bg-primary/70 transition-all" style={{ height: `${20 + ((point.rating - min) / Math.max(1, max - min)) * 80}%` }} /><p className="mt-2 text-center text-[10px] font-bold">{point.rating}</p></div>)}</div><p className="mt-4 text-sm text-muted-foreground">{data.trend >= 0 ? "+" : ""}{data.trend} nelle ultime 5 partite</p></div> : <p className="py-6 text-center text-sm text-muted-foreground">Il grafico apparirà dopo la prima partita completata.</p>}</CardContent></Card>; }
function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <Card><CardContent><span className="text-primary [&_svg]:size-4">{icon}</span><p className="mt-3 text-2xl font-black">{value}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>; }
function Small({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl bg-muted/40 p-3 text-center"><p className="text-xl font-black">{value}</p><p className="mt-1 text-[10px] uppercase text-muted-foreground">{label}</p></div>; }
