import type { DashboardData } from "./types";

const inThreeDays = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString();
const inFiveDays = new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString();

export const demoDashboardData: DashboardData = {
  source: "demo",
  firstName: "Marco",
  username: "marcor10",
  role: "midfielder",
  avatarUrl: null,
  timezone: "Europe/Rome",
  unreadNotifications: 3,
  nextMatch: {
    id: "demo-next",
    leagueName: "Calcetto del Giovedì",
    title: "Giovedì sotto le luci",
    startsAt: inThreeDays,
    venueName: "Centro Sportivo Aurora",
    city: "Milano",
    format: "5v5",
    going: 8,
    maxPlayers: 10,
    participation: "going",
  },
  lastMatch: null,
  leagues: [
    {
      id: "demo-league",
      name: "Calcetto del Giovedì",
      slug: "calcetto-del-giovedi",
      logoUrl: null,
      city: "Milano",
      members: 12,
      format: "5v5",
      role: "owner",
      nextMatchAt: inThreeDays,
    },
    {
      id: "demo-league-2",
      name: "Sunday League Milano",
      slug: "sunday-league-milano",
      logoUrl: null,
      city: "Milano",
      members: 18,
      format: "7v7",
      role: "member",
      nextMatchAt: inFiveDays,
    },
  ],
  stats: { matches: 24, goals: 11, assists: 16, mvp: 4, overall: 76.4 },
  nearby: [
    {
      id: "nearby-1",
      leagueName: "Milano Five",
      title: "Ultimo posto disponibile",
      startsAt: inFiveDays,
      venueName: "Arena Milano",
      city: "Milano",
      format: "5v5",
      going: 9,
      maxPlayers: 10,
      participation: null,
      distanceKm: 2.4,
    },
    {
      id: "nearby-2",
      leagueName: "Navigli Football",
      title: "Partita open",
      startsAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
      venueName: "Sporting Club",
      city: "Milano",
      format: "7v7",
      going: 11,
      maxPlayers: 14,
      participation: null,
      distanceKm: 5.8,
    },
  ],
};
